### ISSUE TITLE
暂无配置了aapt的agent，无法执行aapt dump

### ISSUE THREAD

**Issue by lsp84ch83** [opendx/server#14]
已经指定aapt版本和路径，在App-点击 aapt dump 的时候还是提示 无法执行

![image](https://user-images.githubusercontent.com/25055457/105695660-4dedb580-5f3d-11eb-9c42-474dd1338adb.png)

![image](https://user-images.githubusercontent.com/25055457/105695693-547c2d00-5f3d-11eb-9ea4-d0941d16267b.png)

**Comment by jiangyitao** [comment]
环境问题
