### ISSUE TITLE
展示界面元素结构出错

### ISSUE THREAD

**Issue by loveiset** [opendx/server#2]
日志：https://gist.github.com/loveiset/3819a5b5005583de06fba660cd7e6d31
![Snipaste_2019-08-15_18-00-21](https://user-images.githubusercontent.com/3335977/63088260-fcd74500-bf86-11e9-93ba-740d945399b4.png)

**Comment by jiangyitao** [comment]
特定页面不行吗，还是所有页面

**Comment by loveiset** [comment]
我这一台测试机，换了好几个app，都报这个错，没成功过，我用uiautomatorviewer查看是ok的，而且看日志appium返回也是正常的200

**Comment by jiangyitao** [comment]
先换个手机玩吧，我估计这个手机dump下来的页面xml，处理的有问题

**Comment by jiangyitao** [comment]
@loveiset 
[agent.zip](https://github.com/opendx/server/files/3505264/agent.zip)

agent.jar替换成这个试试 我加了一个saxReader.setEncoding("UTF-8");。不知道会不会报错

**Comment by loveiset** [comment]
@jiangyitao 不太行，更换了agent也不行
我两台手机都试了，都没法展示页面结构，没其他手机了。。

**Comment by jiangyitao** [comment]
@loveiset 用新的agent，重新启动了agent.jar也不行吗

**Comment by loveiset** [comment]
是的哈

**Comment by jiangyitao** [comment]
[agent-0.1.0-beta.zip](https://github.com/opendx/server/files/3507919/agent-0.1.0-beta.zip)
用这个再试试，辛苦了 @loveiset

**Comment by loveiset** [comment]
@jiangyitao 这个ok，能正常展示xml结构

**Comment by jiangyitao** [comment]
@loveiset 多谢反馈，编码问题https://github.com/opendx/agent/commit/f88d3967725e073b044803e861b8eec30011bf4d
